import Link from "next/link";

export const metadata = {
  title: "Terms and Conditions | Inox Secure",
  description:
    "Read the terms and conditions and key information for using Inox Secure’s services and products across India.",
};

export default function TermsPage() {
  return (
    <div>
      {/* Hero Section */}
      <div className="bg-gradient-to-r from-blue-500 via-blue-600 to-transparent">
        <div className="flex flex-col items-center text-center mb-16 px-10 py-10 w-full text-white">
          <h1 className="text-4xl md:text-5xl font-bold mb-6">
            Terms and Conditions
          </h1>
          <p className="text-lg text-white max-w-3xl">
            Please read these terms and conditions carefully before using our
            services.
          </p>
        </div>
      </div>


      <main className="container mx-auto max-w-4xl px-6 py-10 space-y-12">
        {/* ------------ Title ------------ */}
        <header className="text-center">
          <h1 className="text-4xl font-bold mb-2">Terms &amp; Conditions</h1>
        </header>

        {/* ------------ 1. Intro ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>Welcome to Inoxsecure!</h2>
          <p>
            The portal <strong>www.inoxsecure.com</strong>  and its (collectively, “inoxsecure ”), is managed and operated inoxsecure services inoxsecure”, “we”, “us” or “our”. Any natural or legal person who accesses and/or uses inoxsecure in any manner (“you” or “ your”) or uses any current or future service or functionality or offer made available on inoxsecure (“Service ”) will be subject to these terms and conditions for use of inoxsecure (“ Terms of Use”), as updated from time to time and such terms, guidelines and conditions as may be applicable to such Service (“ Service Terms”). If these Terms of Use are inconsistent with such Service Terms, the Service Terms will control to the extent of such inconsistency with respect to the applicable Service.
            These Terms of Use constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures. Please read these Terms of Use carefully before using or accessing inoxsecure or availing any Service.

          </p>
          <p className="font-semibold">
            By using the site, you agree to these Terms. Please read them
            carefully.
          </p>
        </section>

        {/* ------------ 2. Right to Use ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>1 · Right to Use</h2>
          <p>
            Upon execution of this Agreement, you are granted the right to use the Product and Service in accordance with the terms of this Agreement.
            You agree and acknowledge that inoxsecure is an online platform that enables you to purchase the products listed on inoxsecure at the indicated price at any time from the serviceable locations.
            Except where we are the seller of the relevant product on inoxsecure, you agree and acknowledge that we are only a facilitator and are not and cannot be a party to or control in any manner any transactions on inoxsecure.
            Accordingly, such contract of sale of products on the website shall be a strictly bipartite contract between you and the sellers on inoxsecure.
          </p>
        </section>


        {/* ------------ 3. Eligibility ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>2&nbsp;· Eligibility</h2>
          <p>Only persons who can enter into legally binding contracts as per Indian Contract Act, 1872, i.e. persons who are 18 years of age or older, are of sound mind, and are not disqualified from entering into contracts by any law, can use and access inoxsecure. If you are a minor i.e. under the age of 18 years, you may use inoxsecure only with the involvement of a parent or guardian.</p>
        </section>

        {/* ------------ 4. Client Responsibilities ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>3&nbsp;·CLIENT’S RESPONSIBILITIES</h2>
          <p>
            Effective use of Product and Service provided by inoxsecure  presumes a certain degree of knowledge and skill on the part of the Client. We will not be held responsible for your inability to use our Product and Service due to your lack of the requisite knowledge and skills.
          </p>
        </section>

        {/* ------------ 5. Service Fees ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>4&nbsp;·&nbsp;SERVICE&nbsp;FEE</h2>
          <p>
            You agree to pay a three-month money-back guarantee refundable Service Fee for the Services, which will be determined by inoxsecure at the time of accepting the Service.
            The ("Service Fee") shall be paid by you in advance, and inoxsecure will send the customer receipt/invoice to your registered mobile number and email ID simultaneously after receiving the payment.
            inoxsecure shall, at its sole discretion, reserve the right to decide the Service Fee for the Services.
            If the customer connects with you and you benefit, then the company will charge you according to the customer at Rs&nbsp;299, which will be deducted from your wallet balance.
          </p>
        </section>


        {/* ------------ 6. Documents ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>5&nbsp;·&nbsp;Documents</h2>
          <p>
            You shall furnish the KYC documents or any other documents as may be required by inoxsecure.
            For the purpose of clarity, KYC documents include:
            (1)&nbsp;Passport;&nbsp;
            (2)&nbsp;Driving&nbsp;License;&nbsp;
            (3)&nbsp;Voter's&nbsp;Identity&nbsp;Card issued by the Election Commission of India;&nbsp;
            (4)&nbsp;Copy of Aadhar Card;&nbsp;
            (5)&nbsp;Job card issued by NREGA duly signed by an officer of the State Government;&nbsp;
            (6)&nbsp;Letter issued by the National Population Register containing name and address details;&nbsp;
            along with PAN Card, etc.
            In addition to the above, you also need to provide documents related to business listing such as Certificate of Incorporation, PAN Card of the company, Registration Certificate, GST Certificate, Shop&nbsp;&amp;&nbsp;Establishment Certificate, or any other Government-issued certificate required to run the business.
          </p>
        </section>


        {/* ------------ 7. ISSUANCE OF INVOICE ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>6&nbsp;·&nbsp;Issuance&nbsp;of&nbsp;Invoice</h2>
          <p>
            inoxsecure will issue an invoice to you containing, inter&nbsp;alia, the following details: client details, license fees, description of the software features (if required), and the type of access chosen by you (such as website access), if applicable.
          </p>
        </section>


        {/* ------------ 8 Taxes ------------ */}
        <section className="prose prose-lg max-w-none space-y-8">
          <h2>7&nbsp;·&nbsp;Taxes</h2>
          <p>
            inoxsecure is entitled to levy all applicable taxes and charges (now in force or enacted in the future) on the Services provided.
            You shall pay these taxes and charges promptly without raising any objections.
            You also agree that, in the event these taxes and charges are not collected by inoxsecure, you shall pay them directly to the concerned authorities without any objection.
            You further agree that the taxes and charges payable under this clause are in addition to the license fee paid by you for the services rendered by inoxsecure.
            The taxes may include Service Tax, VAT (Value Added Tax), or any other applicable taxes.
          </p>
        </section>


        {/* ------------ 9. Force Majeure ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>8&nbsp;· Force Majeure</h2>
          <p>
            Neither party is liable for delay or failure caused by events beyond
            reasonable control, such as natural disasters or war.
          </p>
        </section>

        {/* ------------ 18. Governing Law ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>18&nbsp;· Governing Law</h2>
          <p>
            These Terms are governed by the laws of India. Jaipur courts have
            exclusive jurisdiction.
          </p>
        </section>

        {/* ------------ 19. Notices ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>19&nbsp;· Notices</h2>
          <p>
            Write to us at&nbsp;
            <a href="mailto:india@inoxsecure.com">india@inoxsecure.com</a> or
            Inoxsecure, Bangalore, India for any legal notice.
          </p>
        </section>

        {/* ------------ Footer ------------ */}
        <footer className="bg-gray-50 p-6 rounded-lg text-center text-sm text-gray-600">
          By using our Services, you confirm that you have read, understood and
          agree to these Terms &amp; Conditions.
        </footer>
      </main>


    </div>
  );
}
