import Link from "next/link";

export const metadata = {
  title: "Terms and Conditions | Inox Secure",
  description:
    "Read the terms and conditions and key information for using Inox Secure’s services and products across India.",
};

export default function TermsPage() {
  return (
    <div>
      {/* Hero Section */}
      <div className="bg-gradient-to-r from-blue-500 via-blue-600 to-transparent">
        <div className="flex flex-col items-center text-center mb-16 px-10 py-10 w-full text-white">
          <h1 className="text-4xl md:text-5xl font-bold mb-6">
            Terms and Conditions
          </h1>
          <p className="text-lg text-white max-w-3xl">
            Please read these terms and conditions carefully before using our
            services.
          </p>
        </div>
      </div>


      <main className="container mx-auto max-w-4xl px-6 py-10 space-y-12">
        {/* ------------ Title ------------ */}
        <header className="text-center">
          <h1 className="text-4xl font-bold mb-2">Terms &amp; Conditions</h1>
        </header>

        {/* ------------ 1. Intro ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>Welcome to Inoxsecure!</h2>
          <p>
            The portal <strong>www.inoxsecure.com</strong>  and its (collectively, “inoxsecure ”), is managed and operated inoxsecure services inoxsecure”, “we”, “us” or “our”. Any natural or legal person who accesses and/or uses inoxsecure in any manner (“you” or “ your”) or uses any current or future service or functionality or offer made available on inoxsecure (“Service ”) will be subject to these terms and conditions for use of inoxsecure (“ Terms of Use”), as updated from time to time and such terms, guidelines and conditions as may be applicable to such Service (“ Service Terms”). If these Terms of Use are inconsistent with such Service Terms, the Service Terms will control to the extent of such inconsistency with respect to the applicable Service.
            These Terms of Use constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures. Please read these Terms of Use carefully before using or accessing inoxsecure or availing any Service.

          </p>
          <p className="font-semibold">
            By using the site, you agree to these Terms. Please read them
            carefully.
          </p>
        </section>

        {/* ------------ 2. Right to Use ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>1 · Right to Use</h2>
          <p>
            Upon execution of this Agreement, you are granted the right to use the Product and Service in accordance with the terms of this Agreement.
            You agree and acknowledge that inoxsecure is an online platform that enables you to purchase the products listed on inoxsecure at the indicated price at any time from the serviceable locations.
            Except where we are the seller of the relevant product on inoxsecure, you agree and acknowledge that we are only a facilitator and are not and cannot be a party to or control in any manner any transactions on inoxsecure.
            Accordingly, such contract of sale of products on the website shall be a strictly bipartite contract between you and the sellers on inoxsecure.
          </p>
        </section>


        {/* ------------ 3. Eligibility ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>2&nbsp;· Eligibility</h2>
          <p>Only persons who can enter into legally binding contracts as per Indian Contract Act, 1872, i.e. persons who are 18 years of age or older, are of sound mind, and are not disqualified from entering into contracts by any law, can use and access inoxsecure. If you are a minor i.e. under the age of 18 years, you may use inoxsecure only with the involvement of a parent or guardian.</p>
        </section>

        {/* ------------ 4. Client Responsibilities ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>3&nbsp;·CLIENT’S RESPONSIBILITIES</h2>
          <p>
            Effective use of Product and Service provided by inoxsecure  presumes a certain degree of knowledge and skill on the part of the Client. We will not be held responsible for your inability to use our Product and Service due to your lack of the requisite knowledge and skills.
          </p>
        </section>

        {/* ------------ 5. Service Fees ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>4&nbsp;·&nbsp;SERVICE&nbsp;FEE</h2>
          <p>
            You agree to pay a three-month money-back guarantee refundable Service Fee for the Services, which will be determined by inoxsecure at the time of accepting the Service.
            The ("Service Fee") shall be paid by you in advance, and inoxsecure will send the customer receipt/invoice to your registered mobile number and email ID simultaneously after receiving the payment.
            inoxsecure shall, at its sole discretion, reserve the right to decide the Service Fee for the Services.
            If the customer connects with you and you benefit, then the company will charge you according to the customer at Rs&nbsp;299, which will be deducted from your wallet balance.
          </p>
        </section>


        {/* ------------ 6. Documents ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>5&nbsp;·&nbsp;Documents</h2>
          <p>
            You shall furnish the KYC documents or any other documents as may be required by inoxsecure.
            For the purpose of clarity, KYC documents include:
            (1)&nbsp;Passport;&nbsp;
            (2)&nbsp;Driving&nbsp;License;&nbsp;
            (3)&nbsp;Voter's&nbsp;Identity&nbsp;Card issued by the Election Commission of India;&nbsp;
            (4)&nbsp;Copy of Aadhar Card;&nbsp;
            (5)&nbsp;Job card issued by NREGA duly signed by an officer of the State Government;&nbsp;
            (6)&nbsp;Letter issued by the National Population Register containing name and address details;&nbsp;
            along with PAN Card, etc.
            In addition to the above, you also need to provide documents related to business listing such as Certificate of Incorporation, PAN Card of the company, Registration Certificate, GST Certificate, Shop&nbsp;&amp;&nbsp;Establishment Certificate, or any other Government-issued certificate required to run the business.
          </p>
        </section>


        {/* ------------ 7. ISSUANCE OF INVOICE ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>6&nbsp;·&nbsp;Issuance&nbsp;of&nbsp;Invoice</h2>
          <p>
            Inoxsecure will issue an invoice to you containing, inter&nbsp;alia, the following details: client details, license fees, description of the software features (if required), and the type of access chosen by you (such as website access), if applicable.
          </p>
        </section>


        {/* ------------ 8 Taxes ------------ */}
        <section className="prose prose-lg max-w-none space-y-8">
          <h2>7&nbsp;·&nbsp;Taxes</h2>
          <p>
            Inoxsecure is entitled to levy all applicable taxes and charges (now in force or enacted in the future) on the Services provided.
            You shall pay these taxes and charges promptly without raising any objections.
            You also agree that, in the event these taxes and charges are not collected by inoxsecure, you shall pay them directly to the concerned authorities without any objection.
            You further agree that the taxes and charges payable under this clause are in addition to the license fee paid by you for the services rendered by inoxsecure.
            The taxes may include Service Tax, VAT (Value Added Tax), or any other applicable taxes.
          </p>
        </section>


        {/* ------------ 9. NON-PERFORMANCE AND DELAYS ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>8&nbsp;· NON-PERFORMANCE AND DELAYSe</h2>
          <p>
            Inoxsecure shall not be liable for any loss or damage resulting from non-performance by inoxsecure or its suppliers under this Agreement or from any delay in delivery of the Product and Service due to fire, labour unrest or strikes, delays in transportation or shipping, acts of God, war, acts of a public enemy, accident, hacking, technical glitch or any other cause or causes beyond the control off
          </p>
        </section>

        {/* ------------ 10. THIRD PARTY CONSULTANT ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>9&nbsp;· THIRD PARTY CONSULTANT</h2>
          <p>
            Inoxsecure will not be liable for any costs incurred as a result of Client, for any reason, employing the services of a third party consultant or other technical personnel.
          </p>
        </section>

        {/* ------------ 11. TRANSFER ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>10&nbsp;·&nbsp;TRANSFER</h2>
          <p>
            This agreement is non-transferable or assignable by the Client without the prior written consent of inoxsecure.
          </p>
        </section>

        {/* ------------ 12. FEES CHANGE ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>11&nbsp;·&nbsp;Fees&nbsp;Change</h2>
          <p>
            inoxsecure reserves the right to increase or change the fees at its discretion.
            The revised fees will become effective only upon renewal of the order.
            For clarity, any additional purchases of the service or other features will be subject to the new pricing.
          </p>
        </section>


        {/* ------------ 13. PERSONAL INFORMATION PRIVACY   ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>12&nbsp;·&nbsp;Personal&nbsp;Information&nbsp;Privacy</h2>
          <p>
            During the course of your registration on and usage of inoxsecure, or while availing the Services, inoxsecure may collect and store, and/or you may provide, personally identifiable and sensitive information about yourself.
            This may include, without limitation, your name, phone number, email address, residential address, postal code, occupation, login details, etc.
          </p>
        </section>

        {/* ------------ 14. TERM AND TERMINATION   ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>13&nbsp;·&nbsp;Term&nbsp;and&nbsp;Termination</h2>
          <p>
            These Terms of Use shall be effective from the date of their publication on inoxsecure.
            inoxsecure reserves the right to terminate the Services in the event of any breach of these Terms of Use, misrepresentation of information, any unlawful activity by you, or if inoxsecure is unable to verify or authenticate any information submitted by you.
            You may terminate these Terms of Use at any time, provided that you discontinue any further use of inoxsecure or its Services.
            However, such termination shall not cancel your obligation to pay for any product purchased on inoxsecure, or any other obligation that has already accrued, remains unfulfilled, or relates to a period prior to termination.
          </p>
        </section>

        {/* ------------ 15. Product Pricing   ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>14&nbsp;·&nbsp;Product&nbsp;Pricing</h2>
          <p>
            All prices are listed in Indian Rupees and are inclusive of all applicable taxes. Products in your shopping cart on inoxsecure will reflect the most recent price as displayed on the product's information page.
            Please note that this price may differ from the price shown when you first added the product to your cart. Placing a product in your shopping cart does not reserve the price shown at that time.
            It is also possible that a product's price may change between the time you place it in your cart and the time you place the order.
            <br /><br />
            The prices mentioned at the time of ordering will be the prices charged on the date of delivery.
            Although prices of most products do not change daily, prices of some items (such as fresh food, vegetables, etc.) may vary.
            In case the price is higher or lower on the delivery date, no additional amount will be collected or refunded, except as specifically stated.
            <br /><br />
            In certain cases, due to high demand, a product listed with a specific price and offer on the Product Detail Page ("PDP") may be available in limited quantities and fulfilled on a first-come, first-served basis.
            If that product goes out of stock, a fresh batch may be delivered instead.
            This new batch may have a different price and may not carry the same discount or offer.
            If you do not agree with the changed price or offer, you may contact our customer care team by email or phone, as mentioned on inoxsecure.
            <br /><br />
            You are responsible for payment of all fees, costs, and charges related to the purchase of products from us, and you agree to bear all applicable taxes.
          </p>
        </section>

        {/* ------------ 16. COMPANY’S LIMITED WARRANTY   ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>15&nbsp;·&nbsp;COMPANY’S LIMITED WARRANTY</h2>
          <p>
            16.1
            The Company agrees to transfer to the Customer all transferable warranties that the Company receives from the manufacturer of the Product(s) that are sold by the Company to the Customer through the Platform.
            16.2
            THE COMPANY MAKES NO OTHER WARRANTY, EXPRESS OR IMPLIED, WITH RESPECT TO THE PRODUCT(S). IN PARTICULAR, THE COMPANY MAKES NO WARRANTY RESPECTING THE MERCHANTABILITY OF THE PRODUCTS OR THEIR SUITABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR USE. THIS WARRANTY EXCLUDES ANY AND ALL OTHER WARRANTIES, WHETHER ORAL, WRITTEN, EXPRESSED, IMPLIED OR STATUTORY.
            16.3
            The Company’s liability arising out of any sale of Product(s) to the Customer is expressly limited to either (i) refund of the purchase price paid by Customer for such Product(s) (without any interest), or (ii) repair and/or replace such Product(s), at the Company’s sole discretion subject to such terms and conditions that may be separately communicated by the Company to the Customer. The Customer must notify the Company within 10(ten working) days from the date of shipment of any defective product.
            16.4
            The Company’s obligations in relation to a notification of defective goods or nonconforming products received from the Customer are solely and exclusively as stated herein. Furthermore, no warranty will apply if the Product has been subject to misuse, static discharge, neglect, accident, modification, or has been soldered, or altered in any way or handled in contravention to any other terms of use that may be communicated by the Company to the Consumer.

          </p>
        </section>

        {/* ------------ 17. DISCLAIMER OF WARRANTY   ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>16&nbsp;·&nbsp;DISCLAIMER OF WARRANTY</h2>
          <p>
            This Product and Service is available to you “as-is whereas basis." You bear the risk of using it. inoxsecure no express warranties, guarantees or conditions inoxsecure will make all reasonable efforts to provide uninterrupted access and hosting services subject to down time and regular maintenance. However, notwithstanding anything in this Agreement, you acknowledge that inoxsecure and its business partners disclaim all warranties including but not limited to express or implied, written or oral. inoxsecure shall not be responsible or liable if any unauthorized person hacks into or gains access to your website. In addition inoxsecure shall not be liable to you for any loss or damage whatsoever or howsoever caused or arising, directly or indirectly, including without limitation, as a result of loss of data or business; interruption or stoppage to the access to and/or use of our service; interruption or stoppage of services etc inoxsecure does not warrant that hosting services will be provided uninterrupted or free from errors or it is free from any virus or other malicious, destructive or corrupting code, program or macro. No advice or information, whether oral or written, obtained by you from inoxsecure or through or from inoxsecure shall create any warranty. inoxsecure shall have no liability in this respect. ii) inoxsecure sole obligation and the your sole and exclusive remedy in the event of interruption services, or loss of use and/or access to service, shall be to use all reasonable endeavors to restore the Services as soon as reasonably possible.

          </p>
        </section>

        {/* ------------ 18. COMPLIANCE WITH APPLICABLE LAW ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>17&nbsp;·&nbsp;Compliance&nbsp;with&nbsp;Applicable&nbsp;Law</h2>
          <p>
            The Company shall identify and list only those product(s) on its platform that are compliant with the Reduction in the Use of Hazardous Substances (RoHS) Directive, in addition to any other applicable laws.
            Any product(s) listed on the platform shall be advertised or confirmed as compliant with all applicable laws by the Company only after sufficient evidence has been received internally from the component manufacturer who sold such product(s) to the Company.
            <br /><br />
            IN NO EVENT SHALL THE COMPANY BE LIABLE FOR ANY SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY NATURE INCLUDING, BUT NOT LIMITED TO, DAMAGES RESULTING FROM LOSS OF PROFIT OR REVENUE, RECALL COSTS, CLAIMS FOR SERVICE INTERRUPTIONS OR FAILURE TO SUPPLY, DOWNTIME, TESTING, INSTALLATION OR REMOVAL COSTS, COSTS OF SUBSTITUTE PRODUCTS, PROPERTY DAMAGE, PERSONAL INJURY, DEATH, OR LEGAL EXPENSES.
            <br /><br />
            The customer shall only be entitled to recover a maximum amount not exceeding the purchase price paid for such product(s) for which a claim is raised against the Company, irrespective of the nature of the claim (whether in warranty, contract, or otherwise).
            <strong> The customer shall indemnify, defend, and hold harmless the Company from any claims raised by any party in relation to the product(s) supplied by the Company to the customer.</strong>
          </p>
        </section>

        {/* ------------ 19. Product Safety and Restrictions ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>18&nbsp;·&nbsp;Product&nbsp;Safety&nbsp;and&nbsp;Restrictions</h2>
          <p>
            The product(s) listed and supplied through the platform to customers are intended for commercial use only. No customer shall use the product(s) for personal use or personal consumption.
            <br /><br />
            Certain product(s) are traceable to the original equipment manufacturer and lot/date code where available and when requested at the time of placing the order. The Company does not determine the specifications or conduct any performance or safety testing of any product(s) it sells to customers.
            <br /><br />
            Any specification sheets provided by the Company to customers, upon written request, are produced solely by the manufacturer of the product(s) or components, or transcribed from manufacturer-supplied information. The Company is not a supplier of Qualified Product Listing (QPL) components. Any reference to military specifications is for reference only and does not modify these Terms and Conditions.
            <br /><br />
            The Company does not participate in product safety engineering, product safety review, or product safety testing, and does not provide safety evaluation or safety engineering services to any customer or third party.
            <br /><br />
            Products sold by the Company are not designed, intended, or authorized for use in life support, life-sustaining, human implantable devices, nuclear facilities, flight control systems, or other applications where failure could result in personal injury, loss of life, or catastrophic property damage. This includes, but is not limited to, Class III medical devices. If a customer sells the product(s) for such uses: (i) the customer acknowledges that such sale is at their own risk; (ii) the customer agrees the Company shall not be liable, in whole or in part, for any claim or damage arising from such sale; and (iii) <strong>the customer agrees to indemnify, defend, and hold the Company harmless from any and all claims, damages, losses, costs, expenses, and liabilities related to such use or sale.</strong>
            <br /><br />
            <strong>Statements and Advice:</strong> If any statements, opinions, or advice (technical or otherwise) are given to a customer, they shall be considered indicative only, and not charged separately. The Company shall not be responsible for the content or use of such advice. The Company does not conduct product suitability studies or engineering reviews for products listed on the platform and has limited participation in product design.
            <br /><br />
            <strong>Intellectual Property:</strong> The Company is the sole owner or lawful licensee of all rights and interests in the platform and its content. All title, ownership, and intellectual property rights remain with the Company or its licensors. All rights not expressly granted are reserved.
            <br /><br />
            If an order includes software or other intellectual property, it may be provided subject to its own copyright and user license terms, as outlined in a separate license agreement. This section does not grant any license or right to use software unless specifically permitted by a separate agreement. Unopened software may be returned for credit, while opened software is non-returnable unless factory defective.
            <br /><br />
            The Company respects third-party intellectual property rights. If any third-party entity believes its rights have been violated, it may contact the grievance officer at <a href="mailto:india@inoxsecure.com">india@inoxsecure.com</a> for prompt resolution.
          </p>
        </section>

        {/* ------------ 20. Content Ownership ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>19&nbsp;·&nbsp;Content&nbsp;Ownership</h2>
          <p>
            inoxsecure maintains control and ownership of any and all IP numbers and addresses that may be assigned to the client, and reserves the right, at its sole discretion, to change or remove any such IP numbers and addresses.
            <br /><br />
            The client shall retain ownership and usage rights of their own domain name(s), even if the client discontinues services with inoxsecure. In the event of any disputes regarding authority over domain names, inoxsecure will follow the industry-standard practice of giving ultimate authority to the domain name registrant.
            <br /><br />
            inoxsecure maintains control and ownership of all copyright, proprietary and/or licensed software, scripts, programs, images, or other electronic data or media installed and/or provided by inoxsecure.
            <br /><br />
            All content stored by you shall remain your property at all times. However, you grant inoxsecure a non-exclusive, worldwide license to your content solely to the extent necessary for inoxsecure to host your website.
            <br /><br />
            inoxsecure may use the information it collects through software features to upgrade or fix the software and to improve its products and services.
            <br /><br />
            Additionally, you agree that inoxsecure may use and disclose such information and that you are deemed to have consented to being contacted for any business promotion by inoxsecure or its affiliates.
          </p>
        </section>

        {/* ------------ 21. Privacy ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>20&nbsp;·&nbsp;Privacy</h2>
          <p>
            Inoxsecure and the client shall mutually keep all data private and will not share or reuse each other's data. Both parties agree to implement all reasonable and standard security measures to protect such data, including signing relevant non-disclosure agreements (NDAs) with their employees and contractors.
            <br /><br />
            The client acknowledges that inoxsecure may be legally required to provide data to authorized legal authorities upon receiving a valid legal injunction. inoxsecure must comply with such injunctions, with or without the client's consent or authorization.
            <br /><br />
            Furthermore, the client understands that there is no absolute guarantee of security. Therefore, to minimize risk in case of accidental exposure, the client agrees not to use the hosting storage for any data beyond what is necessary for hosting operations.
            <br /><br />
            The client authorizes inoxsecure to back up and archive the servers, both on-site and off-site, including the client's data and websites, for the purpose of ensuring continuous hosting operations. inoxsecure may also maintain server logs as required for technical operations and legal compliance. However, this authorization does not obligate inoxsecure to create or maintain such backups, archives, or logs.
            <br /><br />
            In case of suspected unauthorized use or any complaints, inoxsecure may, but is not obligated to, inspect the client's data and traffic for compliance checking before taking any further action.
          </p>
        </section>

        {/* ------------ 22. Miscellaneous ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>21&nbsp;·&nbsp;Miscellaneous</h2>
          <p>
            <strong>No Guarantee of Business:</strong> inoxsecure does not guarantee that by installing and using this software, your business or profit will increase.
            <br /><br />
            <strong>No Marketing:</strong> inoxsecure is not obligated to market or promote your business. inoxsecure's obligation under this contract is limited to providing access to the software after receiving the required payment from you.
            <br /><br />
            <strong>Entire Agreement:</strong> This agreement constitutes the entire understanding between the parties and supersedes any previous agreement, understanding, or promise regarding the software.
            <br /><br />
            <strong>Supersession:</strong> This agreement overrides all prior agreements and understandings (whether written or oral) between inoxsecure and the client(s) related to this subject matter.
            <br /><br />
            <strong>Amendment:</strong> inoxsecure reserves the right to modify the Terms of Service as it deems appropriate, without being required to provide specific notice of such changes to you.
          </p>
        </section>

        {/* ------------ 23. FORCE MAJEURE ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>22&nbsp;·&nbsp;FORCE MAJEURE</h2>
          <p>
            Neither the Company nor the Customers shall be liable for any failure to perform their obligations under these Terms and Conditions for any cause beyond reasonable control including, but not limited to, acts of God, earthquake, epidemic, pandemic, storm, tempest, flood, fire or other natural calamity, riots, war, insurrection, civil commotion, terrorist act, military activity, or act of sabotage, or any event that is outside the control of either party and cannot be remedied or substituted by the Company and/or the Customer with reasonable and prudent commercial efforts.
            The Company’s obligation regarding delivery of the Products and/or any other obligation under these Terms and Conditions shall be extended by the period of such delay or the Company may, at its sole discretion, cancel any order or remaining part thereof, without any liability by giving notice to Customer.

          </p>
        </section>


        {/* ------------ 24. General ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>23&nbsp;·&nbsp;General</h2>
          <p>
            <strong>23.1</strong> These Terms and Conditions shall not be modified, amended, or canceled without the Company's written approval.
            <br /><br />
            <strong>23.2</strong> All product(s) and services, if any, provided by the Company to its customers shall be governed solely by these Terms and Conditions, the Company’s policy, and all applicable laws. This applies regardless of any contrary or additional terms in purchase orders, planning schedules, acknowledgements, confirmations, or other documents between the Company and the customer.
            <br /><br />
            <strong>23.3</strong> Any conflicting statements or terms listed on the customer's purchase orders, invoices, confirmations, or similar documents shall be superseded by any credit application filed with the Company. The issuance of credit by the Company shall prevail over such terms.
            <br /><br />
            <strong>23.4</strong> The performance of any agreement between the Company and the customer shall be governed by these Terms and Conditions unless otherwise agreed to in writing. In the absence of such agreement, the commencement of performance or delivery by the Company shall follow these Terms and Conditions and shall not imply acceptance of any other terms by the customer.
            <br /><br />
            <strong>23.5</strong> No rights, duties, agreements, or obligations may be assigned or transferred by the customer to any third party without the prior written consent of the Company. These Terms and Conditions shall be binding on the customer and its successors or permitted assigns.
            <br /><br />
            <strong>23.6</strong> A waiver of any breach, condition, or default shall not be considered a waiver of any other term or any future breach or default.
            <br /><br />
            <strong>23.7</strong> If any provision of these Terms is found to be prohibited or unenforceable in a specific jurisdiction, it will only be ineffective to that extent and only in that jurisdiction. The rest of the Terms will remain valid.
            <br /><br />
            <strong>23.8</strong> These Terms and Conditions shall be governed by and interpreted according to the laws of the Republic of India.
          </p>
        </section>


        {/* ------------ 25. Notice ------------ */}
        <section className="prose prose-lg max-w-none">
          <h2>24&nbsp;·&nbsp;Notice</h2>
          <p>
            All notices or demands addressed to the Company shall be made in writing and sent to the Company by (a) prepaid registered post acknowledgement due; (b) nationally recognized courier service; or (c) facsimile transmission (confirmation copies of the original document to be sent by mail) to the following email address and postal address: india@inoxsecure.com,jaipur India. The Company may, from time to time, change its address or, representatives for receipt of notices or other communications provided for under these Terms and Conditions by displaying such change on the Platform.
          </p>
        </section>









        {/* ------------ Footer ------------ */}
        <footer className="bg-gray-50 p-6 rounded-lg text-center text-sm text-gray-600">
          By using our Services, you confirm that you have read, understood and
          agree to these Terms &amp; Conditions.
        </footer>
      </main>


    </div>
  );
}
